### ISSUE TITLE
Possibility to set TOM type 

### ISSUE THREAD

**Issue by daniaodeh** [almeidasilvaf/BioNERO#12]
Hey again, 
I really like your package :)

I'd prefer to use signed TOM for unsigned network, is it possible to add the option to set Tom type in consensus modules?

reference : https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/TechnicalReports/signedTOM.pdf

Thanks,
Dania

**Comment by almeidasilvaf** [comment]
Hi, @daniaodeh 

That's a great suggestion! Currently, TOM types are selected based on the network type users choose, but one might indeed want to use signed TOM for unsigned networks. 

I will add a parameter where users can specify the TOM type. I'll keep you posted.

Best,
Fabricio

**Comment by daniaodeh** [comment]
Great, thanks!

**Comment by almeidasilvaf** [comment]
Hi, @daniaodeh 

As requested, I included support for user-defined TOM type in the latest version of __BioNERO__ (parameter *TOM_type* of `consensus_modules()`).

Best,
Fabricio
