### ISSUE TITLE
prepare my data

### ISSUE THREAD

**Issue by wjq1981** [almeidasilvaf/BioNERO#13]
Hello.
Thank you for developing such a great software. But I have a question, how do I need to prepare my data? I see that the example gives a 'zma.se' data, but I don't know how to generate it? Can you help me with that?

**Comment by almeidasilvaf** [comment]
Hi, @wjq1981 


Thank you for your feedback!

The input data can be either one of the options below:

- a gene expression matrix (with gene in row names and samples in column names) and a data frame with sample metadata
- a `SummarizedExperiment` object, which is a standard Bioconductor data class that stores quantitative data with associated sample and gene metadata in a single object. For details on how to construct a `SummarizedExperiment` object, you can take a look at [this section of the package's docs](https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html#constructing-a-summarizedexperiment).

If that solves your problem, feel free to close the issue.

Best,
Fabricio
