### ISSUE TITLE
Error in SFT_fit() 

### ISSUE THREAD

**Issue by mezarelab** [almeidasilvaf/BioNERO#14]
Hi, Thanks for your valuable package.
When I'm running the SFT_fit() code, it shows this error and so, I can't find sft. I hope you can help me in this regard.

> sft <- SFT_fit(final_exp, net_type="signed hybrid", cor_method="pearson")
   Power SFT.R.sq slope truncated.R.sq mean.k. median.k. max.k.
1      3    0.555 -1.23          0.971 14.6000  1.27e+01  48.70
2      4    0.847 -1.65          0.990  6.0500  4.30e+00  30.40
3      5    0.936 -1.73          0.991  2.9200  1.67e+00  21.60
4      6    0.955 -1.70          0.976  1.5900  7.01e-01  16.70
5      7    0.979 -1.63          0.993  0.9540  3.18e-01  13.40
6      8    0.985 -1.54          0.993  0.6200  1.56e-01  11.10
7      9    0.904 -1.56          0.897  0.4280  7.95e-02   9.40
8     10    0.301 -2.31          0.226  0.3100  4.07e-02   8.08
9     11    0.302 -2.21          0.236  0.2340  2.23e-02   7.05
10    12    0.926 -1.40          0.923  0.1820  1.26e-02   6.21
11    13    0.936 -1.37          0.934  0.1450  7.17e-03   5.52
12    14    0.902 -1.37          0.902  0.1180  4.23e-03   4.94
13    15    0.292 -1.88          0.139  0.0977  2.39e-03   4.45
14    16    0.293 -1.86          0.139  0.0821  1.38e-03   4.03
15    17    0.292 -1.84          0.138  0.0698  8.47e-04   3.67
16    18    0.928 -1.29          0.926  0.0599  5.03e-04   3.35
17    19    0.959 -1.24          0.959  0.0519  3.04e-04   3.07
18    20    0.956 -1.23          0.959  0.0454  1.83e-04   2.82
Error in `map()`:
ℹ In index: 6.
ℹ With name: ylab.
Caused by error in `.f()`:
! argument "user_env" is missing, with no default
Backtrace:
     ▆
  1. ├─BioNERO::SFT_fit(final_exp, net_type = "signed hybrid", cor_method = "pearson")
  2. │ └─ggpubr::ggscatter(...)
  3. │   ├─base::do.call(.plotter, .opts)
  4. │   └─ggpubr (local) `<fn>`(...)
  5. │     └─purrr::pmap(...)
  6. │       └─purrr:::pmap_("list", .l, .f, ..., .progress = .progress)
  7. │         └─purrr::map(.l, vctrs_vec_compat)
  8. │           └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  9. │             ├─purrr:::with_indexed_errors(...)
 10. │             │ └─base::withCallingHandlers(...)
 11. │             ├─purrr:::call_with_cleanup(...)
 12. │             └─purrr (local) .f(.x[[i]], ...)
 13. │               └─lifecycle::deprecate_soft(...)
 14. │                 └─lifecycle:::is_direct(user_env)
 15. │                   └─lifecycle:::env_inherits_global(env)
 16. │                     └─rlang::is_reference(env, empty_env())
 17. └─base::.handleSimpleError(...)
 18.   └─purrr (local) h(simpleError(msg, call))
 19.     └─cli::cli_abort(...)
 20.       └─rlang::abort(...)

**Comment by almeidasilvaf** [comment]
Hi, @mezarelab

Thank you for your feedback!

You forgot to include your session info, but it seems like you're using an old version of BioNERO. The package no longer imports functions from {ggpubr} since version 1.5.1 (August 2022). We're now on version 1.9.5.

I believe the error will be fixed once you update BioNERO. You can install the latest version directly from GitHub with:

```r
remotes::install_github("almeidasilvaf/BioNERO")
```

Can you give that a try and let me know if it works?

Best,
Fabricio

**Comment by mezarelab** [comment]
> 

Thanks for your response. the problem was solved by installing new version. Before, I installed the older version on Bioconductor (V 1.0.4).
But now, another question raised. Soft threshold which is obtained via SFT_fit() from this package show different results from the original WGCNA package.

**Comment by almeidasilvaf** [comment]
Hi,

Please, always include the code you used to report (potential) problems. I don't know what you used for WGCNA and BioNERO, but `BioNERO::SFT_fit()` relies on `WGCNA::pickSoftThreshold()`, so they should return the same output if parameters are the same. 

I'd assume you probably ran both functions with default parameters and got different results, which makes sense, since the default parameters are not the same in the two packages. Is that what happened?

Best,
Fabricio

**Comment by mezarelab** [comment]
I really appreciate you for quick response. in brief, I did these: 

1) Using a data.fram TPM normalized count, I run 
 final_exp <- exp_preprocess(TNBC, min_exp = 10, variance_filter = TRUE, n=2000)


Then, I tried both these two ways:  

2-1- Using the original WGCNA package workflow:

power=c(c(1:10), seq(from=12, to=18,by=2))
## Call the network topology analysis function
sft=pickSoftThreshold(final_exp, powerVector =power, 
                      networkType = "signed",
                      verbose = 5)
sft.data= sft$fitIndices
##Visualization of soft-threshold
head(sft.data)
a1 <- ggplot(sft.data, aes(Power, SFT.R.sq, label = Power)) +
  geom_point() +
  geom_text(nudge_y = 0.1) +
  geom_hline(yintercept = 0.8, color = 'red') +
  labs(x = 'Power', y = 'Scale free topology model fit, signed R^2') +
  theme_classic()

a2 <- ggplot(sft.data, aes(Power, mean.k., label = Power)) +
  geom_point() +
  geom_text(nudge_y = 0.1) +
  labs(x = 'Power', y = 'Mean Connectivity') +
  theme_classic()

grid.arrange(a1, a2, nrow = 2)






AND; the BioNERO package workflow:
sft <- SFT_fit(final_exp, net_type="signed", cor_method="pearson")
sft$power
power <- sft$power
sft$plot

But the results of soft threshold are different.

**Comment by almeidasilvaf** [comment]
Hi, @mezarelab 

I believe you missed the fact that __WGCNA__ and __BioNERO__ take different data as input. WGCNA uses a transposed gene expression matrix (with samples in rows and genes in columns), while most packages for quantative data analyses (including __BioNERO__) use the opposite (i.e., genes in rows and samples in columns). This is explained in [the documentation](https://search.r-project.org/CRAN/refmans/WGCNA/html/pickSoftThreshold.html) of the function `pickSoftThreshold()`.

I'll close this issue, but feel free to open another issue if you find any problem.

Best,
Fabricio
