### ISSUE TITLE
Update the issue

### ISSUE THREAD

**Issue by 409199** [almeidasilvaf/BioNERO#15]
Hello, how do I update the installation package to the latest version?

**Comment by almeidasilvaf** [comment]
Hi, @409199 

This information is in the **Installation instructions** section of the README. You need to run:

```r
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}

BiocManager::install("almeidasilvaf/BioNERO")
```

Best,
Fabricio

**Comment by 409199** [comment]
With your help I solved this problem. Thank you!

**Comment by 409199** [comment]
With your help I solved this problem. Thank you!
