### ISSUE TITLE
A question about continuous variables

### ISSUE THREAD

**Issue by 409199** [almeidasilvaf/BioNERO#19]
Hello, I would like to ask if it is possible to make this graph for continuous variables? If so, how can I do it?

![93a0c3a187141a08f62b7a63735658e](https://github.com/almeidasilvaf/BioNERO/assets/151431067/a11a50f6-506f-470e-a195-d9c2eb26aff9)

When I type"plot_expression_profile(exp = final_exp,net=net,plot_module=TRUE, modulename="black")",it shows an error：”Continuous value supplied to a discrete scale“

Best

**Comment by almeidasilvaf** [comment]
Hi, 

No, that's not possible. The levels of the discrete variable are used to color the background, as shown in the figure you attached, so a continuous variable would not work well with this figure.

Best,
Fabricio

**Comment by 409199** [comment]
Well, thank you very much for your answer.

Best wish!
