### ISSUE TITLE
Phenotype

### ISSUE THREAD

**Issue by Tang-pro** [almeidasilvaf/BioNERO#21]
Hi, @almeidasilvaf 

My data here does not have phenotypic data, but I have heard of sQTL. Is it possible to use Alternate splicing as a phenotype here?
But there is a problem here, when correlating modules with phenotypes, since the PSI of alternative splicing is the PSI value of each gene, here is how to count the PSI in a sample

**Comment by almeidasilvaf** [comment]
Hi, @Tang-pro 

You can use whatever you have that describes your samples when performing module-trait correlations, but these variables should describe **samples**, not **genes** (that is why they go in the colData slot of the `SummarizedExperiment` object).

It is very unlikely that you do not have any sample metadata variable at all. You can use anything, really (e.g., tissues, conditions, etc). Of course, that would depend on the biological question you're trying to answer. For example, if you want to find modules with genes whose expression levels increase in a particular tissue or condition, you'd use the tissue/condition variable as "trait" here. colData variables to correlate with can be of any nature: continuous, discrete, or categorical. 

Best,
Fabricio

**Comment by Tang-pro** [comment]
Hi, @

I got it, thank you！
