### ISSUE TITLE
Label each top5 hubgene in each modules

### ISSUE THREAD

**Issue by JamesWu7** [almeidasilvaf/BioNERO#22]
Hi! Is it possible to label each top5 hubgene in each modules when I use the plot_gcn function.
thank u in advance

**Comment by almeidasilvaf** [comment]
Hi, @jamesbangbang1126 

Yes, you can do it. Take a look at the example of `plot_gcn()`, for instance (accessible with `?plot_gcn`):

```r
data(filt.se)
gcn <- exp2gcn(filt.se, SFTpower = 18, cor_method = "pearson")
hubs <- get_hubs_gcn(filt.se, gcn)
gcn_edges <- get_edge_list(gcn, module = "brown", filter = TRUE, method = "min_cor")
p <- plot_gcn(gcn_edges, gcn, hubs = hubs, top_n_hubs = 5)
```

To do this for all modules, you can loop through all module names and use them in the `module` argument of `get_edge_list()`. With this example network, you'd do:

```r
# Get module names
modules <- unique(gcn$genes_and_modules$Modules)
modules <- modules[modules != "grey"]

# Create one plot for each module
plots <- lapply(modules, function(x) {
    e <- get_edge_list(gcn, module = x, filter = TRUE, method = "min_cor")
    p <- plot_gcn(e, gcn, hubs = hubs)
    return(p)
})
```

If that answers your question, feel free to close this issue. ;-)

Best,
Fabricio

**Comment by JamesWu7** [comment]
Thank u so much for you reply.
