### ISSUE TITLE
A question about power

### ISSUE THREAD

**Issue by 409199** [almeidasilvaf/BioNERO#25]
Hello
My calculation of the power value is like this： 
lcc_data_exp <- exp_preprocess(lcc_tpm,min_exp = 5,min_percentage_samples = 0.15)
lcc_sft <- SFT_fit(lcc_data_exp,cor_method = "pearson")

Can I use 20 as my power value?
![图片](https://github.com/almeidasilvaf/BioNERO/assets/151431067/2bcd97d0-c369-466b-a151-48afae64237f)

Thank you very much for your answer, and good luck

**Comment by almeidasilvaf** [comment]
Hi, @409199 

Thank you for using __BioNERO__. ;-)

In theory, you can use any value you want for the $\beta$ power, but greater values often lead to a lower mean degree (i.e., your resulting graph will be very sparse, which is not desirable). In your specific case, using $\beta$ = 20 leads to a satisfactory fit to the scale-free model, but an extremely low mean degree. I would recommend changing your input data or network type to check if you get a smaller value for $\beta$. You could, for instance:

- change the way you filtered your data (maybe remove genes that do not vary much across samples, change the minimum expression threshold, etc)
- use another network type. For example, if you're inferring a *signed* network, but you don't care about negative correlations for the question you're trying to answer, you should consider a *signed hybrid* network instead. I myself use *signed hybrid* networks very often.

Does that answer your question?

Best,
Fabricio
