### ISSUE TITLE
How to pass additional arguments to parameters in ComplexHeatmap::pheatmap().

### ISSUE THREAD

**Issue by Galaxy-228** [almeidasilvaf/BioNERO#26]
Hi,
Under the circumstances where the sample size is too large, the default color palette cannot meet the requirements. According to the official documentation: Besides the arguments users can pass to parameters in plot_heatmap(), they can also pass additional arguments to parameters in ComplexHeatmap::pheatmap() to have additional control additional on plot aesthetics.

I would like to ask how to specifically use the ComplexHeatmap::pheatmap() function. I have tried 
'plot_heatmap(exp_filt, col_metadata = sample_info, type = "samplecor", show_rownames = FALSE)+ ComplexHeatmap::pheatmap(color = color_palette)', but it does not work.
<img width="536" alt="066739df078d994d3e29beac5596b60" src="https://github.com/user-attachments/assets/565347b0-c32d-427c-9652-4c5b051bcfc2">

Thanks so much.

**Comment by almeidasilvaf** [comment]
Hi, @Galaxy-228 

Thank you for using __BioNERO__. :)

Users can indeed pass additional arguments to `ComplexHeatmap::pheatmap()`, but some of them are already pre-defined and cannot be changed. Below you can see the source code of `plot_heatmap()`, with arguments that cannot be changed clearly defined:

```r
# Plot heatmap
    hm <- ComplexHeatmap::pheatmap(
        as.matrix(hm_attr$mat),
        name = hm_attr$name,
        color = hm_attr$pal,
        border_color = NA,
        annotation_row = row_metadata,
        annotation_col = col_metadata,
        main = hm_attr$title,
        annotation_colors = annotation_colors,
        ...
    )
```

All other arguments that are not pre-defined in this code chunk can be changed (this is the purpose of the `...` in the function call).

The color palette that `plot_heatmap()` uses is called [D3 category20](https://nanx.me/ggsci/reference/pal_d3.html), and it's arguably the most popular color palette for a large number of discrete categories (up to 20). The human eye cannot distinguish too many colors, so I don't see how changing palettes would be helpful in your case; 20 colors is already the maximum for meaningful data visualization. Have you considered merging some of these categories?

Best,
Fabricio

**Comment by Galaxy-228** [comment]
Thanks for your reply and suggestions,I will considered merging some of these categories to solved the issues. 

I have another question: After constructing the network, does the largest network (such as the module of black) need to be considered in subsequent analysis? Because in the analysis of WGCNA software, the largest module usually integrates genes that have not been clustered into any module, which is the 'grey' module, usually, this module should not be considered in subsequent analyses.  Is it the same situation in the BioNERO software?
<img width="283" alt="624cbb580b7a26d3c88a9a40b00fcb3" src="https://github.com/user-attachments/assets/3cd23afe-7311-44ff-88ee-dfefbd997836">
<img width="320" alt="491774f18057f35a247234747a6abee" src="https://github.com/user-attachments/assets/159a37a9-cc8a-4f6b-8cad-541e0713092e">


Thanks so much.

**Comment by almeidasilvaf** [comment]
Hi, @Galaxy-228 

Yes, since __BioNERO__ imports WGCNA functions, everything works the same way. The 'grey' module includes genes that cannot be assigned to any module. In your case, the 'black' module is the largest one, but it's still meaningful. The module you should ignore will always be labelled 'grey'.

Best,
Fabricio
