### ISSUE TITLE
minClusterSize ?

### ISSUE THREAD

**Issue by PFRoux** [almeidasilvaf/BioNERO#27]
Dear Almeid,

Thanks a lot for this really nice and user-friendly wrapper around WGCNA.

I was wondering if there is a way to define the minimal size of clusters as it is the case with WGCNA cutreeDynamic function with minClusterSize option ?

Cheers and thanks a lot !

Pierre-François

**Comment by almeidasilvaf** [comment]
Hi, @PFRoux 

Thank you for your feedback and for using {BioNERO}!

Originally, this option was not available, but I have just pushed a new version that includes this option (793e9c65ddfa73e490261486c3fd0a2fd25baa6d). Functions `exp2gcn()` and `exp2gcn_blockwise()` now include a parameter `min_module_size` where users can specify the minimum module size (30 by default). 

You can install the latest version of the package from GitHub with:

```r
remotes::install_github("almeidasilvaf/BioNERO")
```

All the best,
Fabricio

**Comment by PFRoux** [comment]
Thank you so muc ! I am giving a try right now 😊 Have a great day De : Fabrício Almeida-Silva ***@***.***>Date : mercredi, 2 octobre 2024 à 12:46À : almeidasilvaf/BioNERO ***@***.***>Cc : PFRoux ***@***.***>, Mention ***@***.***>Objet : Re: [almeidasilvaf/BioNERO] minClusterSize ? (Issue #27)Hi, @PFRouxThank you for your feedback and for using {BioNERO}!Originally, this option was not available, but I have just pushed a new version that includes this option (793e9c6). Functions exp2gcn() and exp2gcn_blockwise() now include a parameter min_module_size where users can specify the minimum module size (30 by default).You can install the latest version of the package from GitHub with:remotes::install_github("almeidasilvaf/BioNERO")All the best,Fabricio—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
