### ISSUE TITLE
hub genes in consensus modules

### ISSUE THREAD

**Issue by Jigyasa3** [almeidasilvaf/BioNERO#6]
Hi @nturaga  and @almeidasilvaf 

Thank you for a great package and associated vignettes! I am interested in applying the `get_hubs_gcn()` function on the consensus modules. 
The output of  `consensus_modules()` function generates a `isHub` vector. But I am not sure if that's the correct value to extract.
At the same time, would a workaround consisting of extracting hub genes independently in two datasets and then finding if these genes are present in the same/different consensus modules work?

Any suggestions?

**Comment by almeidasilvaf** [comment]
Hi, @Jigyasa3 

Thanks a lot for your feedback.

The function `get_hubs_gcn()` only works on individual GCNs, not on consensus modules. The workaround you suggested is exactly what I would recommend.

Best,
Fabricio
